"""create users and refresh_tokens tables

Revision ID: c3c6264ac0c0
Revises: 001_initial
Create Date: 2026-06-10 18:36:56.996729
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'c3c6264ac0c0'
down_revision: Union[str, None] = '001_initial'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
